services:
  tourplanner-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tourplanner
      POSTGRES_PASSWORD: tourplanner
      POSTGRES_DB: tourplanner
    volumes:
      - "tourplanner-data:/var/lib/postgresql/data"

volumes:
  tourplanner-data: